import type { LucideIcon } from "lucide-react";
import {
  Fingerprint,
  Lock,
  Type,
  FileText,
  Braces,
  Binary,
  Link,
  CaseSensitive,
  Clock,
  KeyRound,
  GitCompareArrows,
  CreditCard,
  Building2,
  Code2,
  Hash,
  Palette,
  Ruler,
  Globe,
  QrCode,
  Grid3x3,
  FileCode,
  BookOpen,
  Scale,
  Database,
  ArrowLeftRight,
  FileSpreadsheet,
  ListChecks,
  SearchCode,
  Table,
  FileDown,
} from "lucide-react";

export type ToolCategory = "Data" | "API" | "Testing" | "Utilities" | "Regional" | "Others";

export interface ToolEntry {
  id: string;
  name: string;
  nameKey: string;
  descriptionKey: string;
  category: ToolCategory;
  href: string;
  icon: LucideIcon;
  popular: boolean;
  recent: boolean;
  keywords: string[];
}

export const toolsCatalog: ToolEntry[] = [
  {
    id: "uuid-generator",
    name: "UUID Generator",
    nameKey: "toolNames.uuid-generator",
    descriptionKey: "uuid-generator.description",
    category: "Data",
    href: "/tools/uuid-generator",
    icon: Fingerprint,
    popular: true,
    recent: false,
    keywords: ["uuid", "guid", "identifier", "random", "generator", "v4"],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    nameKey: "toolNames.password-generator",
    descriptionKey: "password-generator.description",
    category: "Data",
    href: "/tools/password-generator",
    icon: Lock,
    popular: true,
    recent: true,
    keywords: ["password", "generator", "secure", "random", "credential", "hash"],
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    nameKey: "toolNames.lorem-ipsum-generator",
    descriptionKey: "lorem-ipsum-generator.description",
    category: "Data",
    href: "/tools/lorem-ipsum-generator",
    icon: Type,
    popular: false,
    recent: true,
    keywords: ["lorem", "ipsum", "placeholder", "text", "dummy", "filler", "content"],
  },
  {
    id: "cpf-generator",
    name: "CPF Generator & Validator",
    nameKey: "toolNames.cpf-generator",
    descriptionKey: "cpf-generator.description",
    category: "Regional",
    href: "/tools/br/cpf-generator",
    icon: FileText,
    popular: false,
    recent: true,
    keywords: ["cpf", "brazil", "brasil", "validator", "generator", "tax", "person"],
  },
  {
    id: "json-formatter",
    name: "JSON Formatter & Minifier",
    nameKey: "toolNames.json-formatter",
    descriptionKey: "json-formatter.description",
    category: "API",
    href: "/tools/json-formatter",
    icon: Braces,
    popular: true,
    recent: true,
    keywords: ["json", "format", "minify", "pretty", "beautify", "validate", "lint"],
  },
  {
    id: "base64-converter",
    name: "Base64 Encode / Decode",
    nameKey: "toolNames.base64-converter",
    descriptionKey: "base64-converter.description",
    category: "API",
    href: "/tools/base64-converter",
    icon: Binary,
    popular: true,
    recent: true,
    keywords: ["base64", "encode", "decode", "convert", "binary", "ascii"],
  },
  {
    id: "url-encoder",
    name: "URL Encode / Decode",
    nameKey: "toolNames.url-encoder",
    descriptionKey: "url-encoder.description",
    category: "API",
    href: "/tools/url-encoder",
    icon: Link,
    popular: false,
    recent: true,
    keywords: ["url", "encode", "decode", "percent", "query", "parameter", "string"],
  },
  {
    id: "case-converter",
    name: "Case Converter",
    nameKey: "toolNames.case-converter",
    descriptionKey: "case-converter.description",
    category: "Utilities",
    href: "/tools/case-converter",
    icon: CaseSensitive,
    popular: false,
    recent: true,
    keywords: ["case", "convert", "camel", "snake", "kebab", "pascal", "uppercase", "lowercase"],
  },
  {
    id: "timestamp-converter",
    name: "Timestamp / Unix Time Converter",
    nameKey: "toolNames.timestamp-converter",
    descriptionKey: "timestamp-converter.description",
    category: "Utilities",
    href: "/tools/timestamp-converter",
    icon: Clock,
    popular: false,
    recent: true,
    keywords: ["timestamp", "unix", "time", "date", "epoch", "converter", "utc"],
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    nameKey: "toolNames.jwt-decoder",
    descriptionKey: "jwt-decoder.description",
    category: "API",
    href: "/tools/jwt-decoder",
    icon: KeyRound,
    popular: false,
    recent: true,
    keywords: ["jwt", "token", "decode", "json", "web", "auth", "bearer"],
  },
  {
    id: "jwt-generator",
    name: "JWT Generator & Signer",
    nameKey: "toolNames.jwt-generator",
    descriptionKey: "jwt-generator.description",
    category: "API",
    href: "/tools/jwt-generator",
    icon: KeyRound,
    popular: false,
    recent: true,
    keywords: ["jwt", "token", "generate", "sign", "hmac", "auth", "bearer", "encoder"],
  },
  {
    id: "json-compare",
    name: "JSON Compare",
    nameKey: "toolNames.json-compare",
    descriptionKey: "json-compare.description",
    category: "API",
    href: "/tools/json-compare",
    icon: GitCompareArrows,
    popular: false,
    recent: true,
    keywords: ["json", "compare", "diff", "difference", "merge", "patch"],
  },
  {
    id: "credit-card-generator",
    name: "Credit Card Test Generator",
    nameKey: "toolNames.credit-card-generator",
    descriptionKey: "credit-card-generator.description",
    category: "Data",
    href: "/tools/credit-card-generator",
    icon: CreditCard,
    popular: false,
    recent: true,
    keywords: ["credit", "card", "visa", "mastercard", "amex", "test", "payment", "luhn"],
  },
  {
    id: "cnpj-generator",
    name: "CNPJ Generator & Validator",
    nameKey: "toolNames.cnpj-generator",
    descriptionKey: "cnpj-generator.description",
    category: "Regional",
    href: "/tools/br/cnpj-generator",
    icon: Building2,
    popular: false,
    recent: true,
    keywords: ["cnpj", "brazil", "brasil", "company", "business", "validator", "tax"],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    nameKey: "toolNames.regex-tester",
    descriptionKey: "regex-tester.description",
    category: "Utilities",
    href: "/tools/regex-tester",
    icon: Code2,
    popular: false,
    recent: true,
    keywords: ["regex", "regular", "expression", "pattern", "match", "test", "grep"],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    nameKey: "toolNames.hash-generator",
    descriptionKey: "hash-generator.description",
    category: "Utilities",
    href: "/tools/hash-generator",
    icon: Hash,
    popular: false,
    recent: true,
    keywords: ["hash", "md5", "sha", "sha256", "sha512", "checksum", "crypto", "digest"],
  },
  {
    id: "color-picker",
    name: "Color Picker & Converter",
    nameKey: "toolNames.color-picker",
    descriptionKey: "color-picker.description",
    category: "Utilities",
    href: "/tools/color-picker",
    icon: Palette,
    popular: false,
    recent: true,
    keywords: ["color", "picker", "hex", "rgb", "hsl", "cmyk", "convert", "design"],
  },
  // === Phase 11: New Tools ===
  // Testing / QA
  {
    id: "boundary-value-calculator",
    name: "Boundary Value Calculator",
    nameKey: "toolNames.boundary-value-calculator",
    descriptionKey: "boundary-value-calculator.description",
    category: "Testing",
    href: "/tools/boundary-value-calculator",
    icon: Ruler,
    popular: false,
    recent: true,
    keywords: ["boundary", "value", "test", "qa", "min", "max", "edge", "case"],
  },
  {
    id: "test-data-generator",
    name: "Test Data Table Generator",
    nameKey: "toolNames.test-data-generator",
    descriptionKey: "test-data-generator.description",
    category: "Testing",
    href: "/tools/test-data-generator",
    icon: Table,
    popular: false,
    recent: true,
    keywords: ["test", "data", "mock", "fake", "csv", "json", "sql", "generator", "table"],
  },
  {
    id: "bdd-gherkin-builder",
    name: "BDD / Gherkin Snippet Builder",
    nameKey: "toolNames.bdd-gherkin-builder",
    descriptionKey: "bdd-gherkin-builder.description",
    category: "Testing",
    href: "/tools/bdd-gherkin-builder",
    icon: ListChecks,
    popular: false,
    recent: true,
    keywords: ["bdd", "gherkin", "given", "when", "then", "scenario", "cucumber", "behavior"],
  },
  {
    id: "http-status-codes",
    name: "HTTP Status Code Reference",
    nameKey: "toolNames.http-status-codes",
    descriptionKey: "http-status-codes.description",
    category: "Testing",
    href: "/tools/http-status-codes",
    icon: Globe,
    popular: false,
    recent: true,
    keywords: ["http", "status", "code", "404", "500", "200", "301", "api", "rest"],
  },
  {
    id: "xpath-css-builder",
    name: "XPath & CSS Selector Builder",
    nameKey: "toolNames.xpath-css-builder",
    descriptionKey: "xpath-css-builder.description",
    category: "Testing",
    href: "/tools/xpath-css-builder",
    icon: SearchCode,
    popular: false,
    recent: true,
    keywords: ["xpath", "css", "selector", "selenium", "locator", "scraping", "automation"],
  },
  // API
  {
    id: "curl-to-code",
    name: "cURL to Code Converter",
    nameKey: "toolNames.curl-to-code",
    descriptionKey: "curl-to-code.description",
    category: "API",
    href: "/tools/curl-to-code",
    icon: Code2,
    popular: false,
    recent: true,
    keywords: ["curl", "convert", "fetch", "axios", "python", "requests", "http", "code"],
  },
  {
    id: "markdown-html-converter",
    name: "Markdown ⇄ HTML Converter",
    nameKey: "toolNames.markdown-html-converter",
    descriptionKey: "markdown-html-converter.description",
    category: "Utilities",
    href: "/tools/markdown-html-converter",
    icon: FileCode,
    popular: false,
    recent: true,
    keywords: ["markdown", "html", "convert", "render", "parse", "document"],
  },
  {
    id: "markdown-pdf-converter",
    name: "Markdown → PDF",
    nameKey: "toolNames.markdown-pdf-converter",
    descriptionKey: "markdown-pdf-converter.description",
    category: "Utilities",
    href: "/tools/markdown-pdf-converter",
    icon: FileDown,
    popular: false,
    recent: true,
    keywords: ["markdown", "pdf", "export", "document", "print", "convert", "report"],
  },
  {
    id: "user-agent-parser",
    name: "User-Agent Parser",
    nameKey: "toolNames.user-agent-parser",
    descriptionKey: "user-agent-parser.description",
    category: "API",
    href: "/tools/user-agent-parser",
    icon: SearchCode,
    popular: false,
    recent: true,
    keywords: ["user-agent", "browser", "parse", "os", "device", "mobile", "desktop", "ua"],
  },
  {
    id: "mime-type-checker",
    name: "MIME Type Checker",
    nameKey: "toolNames.mime-type-checker",
    descriptionKey: "mime-type-checker.description",
    category: "API",
    href: "/tools/mime-type-checker",
    icon: FileSpreadsheet,
    popular: false,
    recent: true,
    keywords: ["mime", "type", "content-type", "extension", "file", "http", "header"],
  },
  // Regional (Brazil)
  {
    id: "cep-generator",
    name: "CEP Generator & Validator",
    nameKey: "toolNames.cep-generator",
    descriptionKey: "cep-generator.description",
    category: "Regional",
    href: "/tools/br/cep-generator",
    icon: FileText,
    popular: false,
    recent: true,
    keywords: ["cep", "brazil", "brasil", "postal", "code", "address", "generator", "validator"],
  },
  {
    id: "renavam-generator",
    name: "Renavam Generator & Validator",
    nameKey: "toolNames.renavam-generator",
    descriptionKey: "renavam-generator.description",
    category: "Regional",
    href: "/tools/br/renavam-generator",
    icon: FileText,
    popular: false,
    recent: true,
    keywords: ["renavam", "brazil", "brasil", "vehicle", "car", "registration", "validator"],
  },
  {
    id: "pix-key-generator",
    name: "PIX Key Generator",
    nameKey: "toolNames.pix-key-generator",
    descriptionKey: "pix-key-generator.description",
    category: "Regional",
    href: "/tools/br/pix-key-generator",
    icon: KeyRound,
    popular: false,
    recent: true,
    keywords: ["pix", "brazil", "brasil", "payment", "key", "transfer", "random", "cpf"],
  },
  // Data
  {
    id: "csv-json-converter",
    name: "CSV ⇄ JSON Converter",
    nameKey: "toolNames.csv-json-converter",
    descriptionKey: "csv-json-converter.description",
    category: "Data",
    href: "/tools/csv-json-converter",
    icon: ArrowLeftRight,
    popular: false,
    recent: true,
    keywords: ["csv", "json", "convert", "data", "export", "import", "table"],
  },
  {
    id: "number-base-converter",
    name: "Number Base Converter",
    nameKey: "toolNames.number-base-converter",
    descriptionKey: "number-base-converter.description",
    category: "Data",
    href: "/tools/number-base-converter",
    icon: Binary,
    popular: false,
    recent: true,
    keywords: ["number", "base", "decimal", "hex", "binary", "octal", "convert", "programming"],
  },
  {
    id: "byte-converter",
    name: "Byte Converter",
    nameKey: "toolNames.byte-converter",
    descriptionKey: "byte-converter.description",
    category: "Data",
    href: "/tools/byte-converter",
    icon: Database,
    popular: false,
    recent: true,
    keywords: ["byte", "kb", "mb", "gb", "tb", "storage", "convert", "unit", "size"],
  },
  // Others
  {
    id: "chmod-calculator",
    name: "Chmod Calculator",
    nameKey: "toolNames.chmod-calculator",
    descriptionKey: "chmod-calculator.description",
    category: "Others",
    href: "/tools/chmod-calculator",
    icon: Grid3x3,
    popular: false,
    recent: true,
    keywords: ["chmod", "linux", "permission", "file", "unix", "octal", "rwx", "security"],
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    nameKey: "toolNames.qr-code-generator",
    descriptionKey: "qr-code-generator.description",
    category: "Others",
    href: "/tools/qr-code-generator",
    icon: QrCode,
    popular: false,
    recent: true,
    keywords: ["qr", "code", "generator", "barcode", "scan", "url", "download", "png"],
  },
  {
    id: "text-binary-converter",
    name: "Text \u21C4 Binary Converter",
    nameKey: "toolNames.text-binary-converter",
    descriptionKey: "text-binary-converter.description",
    category: "Utilities",
    href: "/tools/text-binary-converter",
    icon: Binary,
    popular: false,
    recent: true,
    keywords: ["text", "binary", "convert", "ascii", "encode", "decode", "bits", "encoding"],
  },
  {
    id: "aspect-ratio-calculator",
    name: "Aspect Ratio Calculator",
    nameKey: "toolNames.aspect-ratio-calculator",
    descriptionKey: "aspect-ratio-calculator.description",
    category: "Others",
    href: "/tools/aspect-ratio-calculator",
    icon: Scale,
    popular: false,
    recent: true,
    keywords: ["aspect", "ratio", "image", "width", "height", "dimension", "resize", "16:9"],
  },
];
