import type { LucideIcon } from "lucide-react";
import {
  Fingerprint,
  Lock,
  Type,
  FileText,
  Braces,
  Binary,
  Link,
  CaseSensitive,
  Clock,
  KeyRound,
  GitCompareArrows,
  CreditCard,
  Building2,
  Code2,
  Hash,
  Palette,
} from "lucide-react";

export type ToolCategory = "Data" | "API" | "Testing" | "Utilities" | "Regional" | "Others";

export interface ToolEntry {
  id: string;
  name: string;
  nameKey: string;
  descriptionKey: string;
  category: ToolCategory;
  href: string;
  icon: LucideIcon;
  popular: boolean;
  recent: boolean;
  keywords: string[];
}

export const toolsCatalog: ToolEntry[] = [
  {
    id: "uuid-generator",
    name: "UUID Generator",
    nameKey: "toolNames.uuid-generator",
    descriptionKey: "uuid-generator.description",
    category: "Data",
    href: "/tools/uuid-generator",
    icon: Fingerprint,
    popular: true,
    recent: false,
    keywords: ["uuid", "guid", "identifier", "random", "generator", "v4"],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    nameKey: "toolNames.password-generator",
    descriptionKey: "password-generator.description",
    category: "Data",
    href: "/tools/password-generator",
    icon: Lock,
    popular: true,
    recent: true,
    keywords: ["password", "generator", "secure", "random", "credential", "hash"],
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    nameKey: "toolNames.lorem-ipsum-generator",
    descriptionKey: "lorem-ipsum-generator.description",
    category: "Data",
    href: "/tools/lorem-ipsum-generator",
    icon: Type,
    popular: false,
    recent: true,
    keywords: ["lorem", "ipsum", "placeholder", "text", "dummy", "filler", "content"],
  },
  {
    id: "cpf-generator",
    name: "CPF Generator & Validator",
    nameKey: "toolNames.cpf-generator",
    descriptionKey: "cpf-generator.description",
    category: "Regional",
    href: "/tools/br/cpf-generator",
    icon: FileText,
    popular: false,
    recent: true,
    keywords: ["cpf", "brazil", "brasil", "validator", "generator", "tax", "person"],
  },
  {
    id: "json-formatter",
    name: "JSON Formatter & Minifier",
    nameKey: "toolNames.json-formatter",
    descriptionKey: "json-formatter.description",
    category: "API",
    href: "/tools/json-formatter",
    icon: Braces,
    popular: true,
    recent: true,
    keywords: ["json", "format", "minify", "pretty", "beautify", "validate", "lint"],
  },
  {
    id: "base64-converter",
    name: "Base64 Encode / Decode",
    nameKey: "toolNames.base64-converter",
    descriptionKey: "base64-converter.description",
    category: "API",
    href: "/tools/base64-converter",
    icon: Binary,
    popular: true,
    recent: true,
    keywords: ["base64", "encode", "decode", "convert", "binary", "ascii"],
  },
  {
    id: "url-encoder",
    name: "URL Encode / Decode",
    nameKey: "toolNames.url-encoder",
    descriptionKey: "url-encoder.description",
    category: "API",
    href: "/tools/url-encoder",
    icon: Link,
    popular: false,
    recent: true,
    keywords: ["url", "encode", "decode", "percent", "query", "parameter", "string"],
  },
  {
    id: "case-converter",
    name: "Case Converter",
    nameKey: "toolNames.case-converter",
    descriptionKey: "case-converter.description",
    category: "Utilities",
    href: "/tools/case-converter",
    icon: CaseSensitive,
    popular: false,
    recent: true,
    keywords: ["case", "convert", "camel", "snake", "kebab", "pascal", "uppercase", "lowercase"],
  },
  {
    id: "timestamp-converter",
    name: "Timestamp / Unix Time Converter",
    nameKey: "toolNames.timestamp-converter",
    descriptionKey: "timestamp-converter.description",
    category: "Utilities",
    href: "/tools/timestamp-converter",
    icon: Clock,
    popular: false,
    recent: true,
    keywords: ["timestamp", "unix", "time", "date", "epoch", "converter", "utc"],
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    nameKey: "toolNames.jwt-decoder",
    descriptionKey: "jwt-decoder.description",
    category: "API",
    href: "/tools/jwt-decoder",
    icon: KeyRound,
    popular: false,
    recent: true,
    keywords: ["jwt", "token", "decode", "json", "web", "auth", "bearer"],
  },
  {
    id: "jwt-generator",
    name: "JWT Generator & Signer",
    nameKey: "toolNames.jwt-generator",
    descriptionKey: "jwt-generator.description",
    category: "API",
    href: "/tools/jwt-generator",
    icon: KeyRound,
    popular: false,
    recent: true,
    keywords: ["jwt", "token", "generate", "sign", "hmac", "auth", "bearer", "encoder"],
  },
  {
    id: "json-compare",
    name: "JSON Compare",
    nameKey: "toolNames.json-compare",
    descriptionKey: "json-compare.description",
    category: "API",
    href: "/tools/json-compare",
    icon: GitCompareArrows,
    popular: false,
    recent: true,
    keywords: ["json", "compare", "diff", "difference", "merge", "patch"],
  },
  {
    id: "credit-card-generator",
    name: "Credit Card Test Generator",
    nameKey: "toolNames.credit-card-generator",
    descriptionKey: "credit-card-generator.description",
    category: "Data",
    href: "/tools/credit-card-generator",
    icon: CreditCard,
    popular: false,
    recent: true,
    keywords: ["credit", "card", "visa", "mastercard", "amex", "test", "payment", "luhn"],
  },
  {
    id: "cnpj-generator",
    name: "CNPJ Generator & Validator",
    nameKey: "toolNames.cnpj-generator",
    descriptionKey: "cnpj-generator.description",
    category: "Regional",
    href: "/tools/br/cnpj-generator",
    icon: Building2,
    popular: false,
    recent: true,
    keywords: ["cnpj", "brazil", "brasil", "company", "business", "validator", "tax"],
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    nameKey: "toolNames.regex-tester",
    descriptionKey: "regex-tester.description",
    category: "Utilities",
    href: "/tools/regex-tester",
    icon: Code2,
    popular: false,
    recent: true,
    keywords: ["regex", "regular", "expression", "pattern", "match", "test", "grep"],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    nameKey: "toolNames.hash-generator",
    descriptionKey: "hash-generator.description",
    category: "Utilities",
    href: "/tools/hash-generator",
    icon: Hash,
    popular: false,
    recent: true,
    keywords: ["hash", "md5", "sha", "sha256", "sha512", "checksum", "crypto", "digest"],
  },
  {
    id: "color-picker",
    name: "Color Picker & Converter",
    nameKey: "toolNames.color-picker",
    descriptionKey: "color-picker.description",
    category: "Utilities",
    href: "/tools/color-picker",
    icon: Palette,
    popular: false,
    recent: true,
    keywords: ["color", "picker", "hex", "rgb", "hsl", "cmyk", "convert", "design"],
  },
];
